title = "Jiyuan Zhang"
baseURL = "https://jiyuan.is"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally

[services]
  [services.googleAnalytics]
    id = ""  # add your tracking id

[params]
  author = "Jiyuan Zhang"
  description = "Jiyuan Zhang's Website - A Computer System and Architecture Researcher."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "Researcher Theme By Olivier Roques"
    url = "https://github.com/ojroques/hugo-researcher"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    fontSize = "14pt"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fa-brands fa-github"
    title = "GitHub"
    url = "https://github.com/jiyuzh"
  [[params.socialIcons]]
    icon = "fa-brands fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/jiyuzh/"
  [[params.socialIcons]]
    icon = "fa-brands fa-google-scholar"
    title = "Scholar"
    url = "https://scholar.google.com/citations?user=-8_kT8cAAAAJ"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 2
  [[menu.main]]
    name = "CV"
    url = "/cv.pdf"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
